language: scala
sudo: false
script: sbt -jvm-opts jvmopts.travis test
jdk:
- oraclejdk8
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7053daf92ef3da0554f0
    on_success: change
    on_failure: always
    on_start: false
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "develop" && sbt publish
env:
  global:
  - secure: c0dhTH8MG/yLjvbW/JEjknAjjUDQuzk8e8mQ8vdfcfVybaCTzfOrl7LOjpZIgugbtYfL1E0whT/AepahqFkV6zy2rNTV66UTrdxgGR78vyFROFV0tNHd6HfoFoyJBcYWrXRiFz34JwM3rZAPZsonfMu1sUc55Iql0YvB3Sraxq3wis+0+FIg6v6PdPdcVGERwKZFXFOdRAAcIg056I0qdKk+hLuj4H+WB3RujopFnc6DvJcE8Un3So0tEYbp9cTjMWGZz+rfgdHC8dvlD/rKb3zvhfeLxj/wXbTFqZomxc1NHkYyClE1gjkeL485C099skRfvNinyOxxa/iJX8vbSy/GqdRGCeCtCFjB686+ZvPl1Y+nviSVUVExgRxDRWjAnDBWtl8tuVWs/SX9VgYYtw3iD9Nf1LU2LDRlJ3vFHUsh+7R4k/nktbITVMAf5CpsSHIc+1InZRvQQqTENvuWwbThyMTCf5IgZToVQmfEY4/tgPjf/46cWpTzSq6dbvSlthiBUxgyJ+6/oaOq/gUX6dnbAK4pk9KPwNZVNnZa8p4TSwKReYuNYbGGVcKOKzai1DXF/gwMi9HrOlXOAlaJoWnumg2RUxzKPRoEayB/mo3OqBO59ThaJT20MQHD7uVfFwZ+Elnz42EQbogOVyqVqZBFxkhhGA+PaNCKuhvvw+Q=
  - secure: Zwtqjvq+281NUetMDJKue0djceth+GIJM2x//II290V/DcsXt9LFeyQcpPLI1QxD8kHV4bh5gH+j5zpHFPNcTqBVHXD2jvw2BiESzYdHHv0MRmUPSH9i/Lzebp2qT5Dz5qhM1vWD06MURjaAfnm7IRz0TRNnckOR+OaFp5x7/7/zyumeV2VP7X4o+5IntDkBb/zuEaFrOJRS6Dz/uBP0vGo4rQSFDl1QjX7VxR7iLBBd4mLQIEIagBq7oBq5nuQ0wfNLiPx44Tgwr18e8dlfBxVJyoYwNlNvOoQqmKKIqY6RsjcCJHTSkbtwz50Lj0cpXPR6SXnLTB1TARcn/uPkoLKBjjwIgaTMAe0VBeR9FQiE77DhIBkauPtZU47MFdyXeF0f4TVkrHnRBfDjn38EF4+VRJjJF9cRCsAk0KvB+13LtKY2wsU/t5wYnPDTHqesCDfnOzOs9Ph5xRrPHfhAz7lKm79fKmydJp9ySDKlf54tjekJeqUcOSVo4g1+3DFMrr22J9pdW15FC8HdY9LezH9dKBZHbqyAER5EZkdkfBsAGKf3hAx56koLJy9t+kZ27kbcoUKQhSvbM1mynvltQfeXUHippDVqopA8ukILp04e3xI/OgGPzmOybOqT0ATN5UbuwcSZjZcfug4R2FF7r1YYRp0UOu8PJEnTt6v5hIo=
